name: 'Signal App'
description: 'Send signals to SSC'
author: 'SSC'

inputs:
  github_token:
    description: 'GitHub token'
    required: true
  dependencies:
    description: 'steps.dependabot-metadata.outputs.updated-dependencies-json'
    required: true

runs:
  using: 'node12'
  main: 'signal/dist/main.js'