name: deploy

on:
  release:
    types: [published, released, prereleased]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - run: echo "Building..."
        
      uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: "dsaltares/godot-wild-jam-18"
        version: "latest"
        file: "ui-ssr.zip"
        token: ${{ secrets.YOUR_TOKEN }}

      - run: ls -la